---
- hosts: k8s
  tasks:
    - name: Generate encryption key
      set_fact:
        enc_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"

    - name: Create EncryptionConfig resource
      blockinfile:
        path: "{{ ansible_env.HOME }}/encryption-config.yml"
        create: yes
        block: |
          kind: EncryptionConfig
          apiVersion: v1
          resources:
            - resources:
                - secrets
              providers:
                - aescbc:
                    keys:
                      - name: key1
                        secret: {{ enc_key }}
                - identity: {}

