---
- hosts: all
  become: yes
  tasks:

    - name: Ensure the required kernel modules are loaded
      blockinfile:
        path: /etc/modules-load.d/netfilter.conf
        create: yes
        content: "br_netfilter"

    - name: Reload Systemd modules
      systemd:
        name: systemd-modules-load
        daemon_reload: yes
        state: reloaded
