---
- hosts: all
  vars:
    base_url: "https://storage.googleapis.com/kubernetes-release/release"
    version: "1.18.6"
    target_dir: "/usr/local/bin"
  tasks:
    - name: Get kubectl
      get_url: 
        url: "{{ base_url}}/v{{ version }}/bin/linux/amd64/{{ item }}"
        dest: "{{ target_dir }}"
        mode: "u+x"
      with_items:
        - kubectl
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler


